# SPDX-FileCopyrightText: 2025 Forkbomb BV
#
# SPDX-License-Identifier: AGPL-3.0-or-later

name: 📢 Binaries publish
on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

concurrency:
    group: ${{ github.workflow }}-${{ github.ref_name }}
    cancel-in-progress: true

jobs:
    release:
        name: 🔖 Release
        runs-on: ubuntu-latest
        if: github.ref == 'refs/heads/main'
        permissions:
            contents: write
            attestations: write
            id-token: write
        steps:
            - uses: actions/checkout@v4
              with:
                  submodules: true
            - uses: jdx/mise-action@v2
            - uses: sigstore/cosign-installer@v3.8.1
            - uses: anchore/sbom-action/download-syft@v0.18.0
            - uses: go-semantic-release/action@v1
              with:
                  hooks: goreleaser
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            - uses: actions/attest-build-provenance@v2
              with:
                  subject-checksums: ./dist/checksums.txt
            - name: Update VERSION file
              if: success() && startsWith(github.ref, 'refs/tags/')
              run: |
                  git config --global user.name 'github-actions[bot]'
                  git config --global user.email 'github-actions[bot]@users.noreply.github.com'

                  TAG_NAME=${{ github.ref_name }}

                  echo "Updating VERSION file to ${TAG_NAME}"
                  echo "${TAG_NAME}" > VERSION

                  git checkout main 
                  git pull origin main
                  git add VERSION
                  if git diff --staged --quiet; then
                    echo "No changes to VERSION file to commit."
                  else
                    git commit -m "chore(release): update VERSION to ${TAG_NAME}"
                    git push origin main
                  fi
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
